# site settings
locale: 'en-US'

title: 'Defence Tribune'
description: 'Defence Tribune: A Geopolitical fact sheet.'

baseurl: ''
url: 'https://defencetribune.com'

# asset dir
asset: '/assets'

# plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap


exclude:
   - test
   - init
   - README.md
