# site settings
locale: 'en-US'

title: 'Defence Tribune'
description: 'Defence Tribune'

baseurl: ''
url: 'https://defencetribune.com'

# asset dir
asset: '/assets'

# build config
plugins:
  - jekyll-feed
  - jekyll-paginate


exclude:
   - test
   - init
   - README.md
